language: node_js

node_js: "8"

install:
- npm install

services:
  - mongodb

script:
- npm test

env:
- NODE_ENV=development

cache:
  directories:
  - "node_modules"

before_script:
  - npm install -g grunt-cli
